version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: template-identifier
    build:
      context: ./template-identifier
      dockerfile: Dockerfile
    hostname: template-identifier
    restart: always
    logging: *default-logging